### ISSUE TITLE
Goomba's Garden Capitalization issue

### ISSUE THREAD

**Issue by Lenrocexe** [DeDanny/Mario#6]
You got a small capitalization problem with this stage. Class name is GoombaGardenStart but the constructor is GoombaGardenstart. Notice the s from start.

Files:
mario/Stages/Stage.java -> import and the call at line 187
mario/Stages/GoombasGarden/GoombaGardenStart.java -> class definition and constructor

**Comment by DeDanny** [comment]
Hmm. I've just looked at my computer, but everything was a little s.

But when I looked at the source on GitHub, oops.
I'm now all done with a capital S, as it should.

Thank you.

D.

Now get out of my repository and get amazed at the and of the day ;).
